Adaptive grids for index
htmlacademy-adaptive/1452537-mishka-21 pull request #10
Opened 2020-12-04 23:11 UTC by Nikulichka

2020-12-05 04:31 UTC, Dima-Dim requested changes
`source/img/review.jpg` и `source/img/review_1.jpg` одинаковые?

2020-12-05 04:31 UTC, Dima-Dim commented on source/less/blocks/contacts.less
> +@media (min-width: @tablet-width) {
На практике такой код довольно сложно поддерживать и с этими сложностями можно столкнутся, когда проект довёрстан и начинается подгонка размеров под макет. Дело в том, что, изменяя код для мобилки будет не видно, как описано изменяемое свойство для других разрешений и описано ли вообще, придется листать код туда-сюда и искать что там ниже. Когда кода будет больше, свойства, относящиеся к одному селектору будут слишком далеко друг от друга и сложно будет понимать что и когда происходит. Если же организовать код по такой логике:
.class {
  @media (min-width: @tablet-width) {
    padding: 10px;
  }

  @media (min-width: @desktop-width) {
    padding-top: 70px;
    padding-bottom: 25px;
  }
}
то сразу будет видно повлияют ли правки для одного разрешения на другое.

Повторюсь, это не обязательное условие – это рекомендация.

2020-12-05 04:31 UTC, Dima-Dim commented on source/less/blocks/modal.less
> +.modal-select-size {
Возможно `modal__select-size`

2020-12-05 22:26 UTC, Nikulichka commented on source/less/blocks/contacts.less
> +@media (min-width: @tablet-width) {
Спасибо)

2020-12-07 06:36 UTC, Dima-Dim requested changes

2020-12-07 06:36 UTC, Dima-Dim commented on source/index.html
> +      <div class="modal__wrapper"></div>
Кажется `</div>` здесь лишний.

2020-12-07 06:36 UTC, Dima-Dim commented on source/index.html
> +            <label class="modal__label-size modal__label--active" for="input-size-s">S</label>
`modal__label--active` -> `modal__label-size--active`

2020-12-08 05:08 UTC, merged