Form page for pixelpefect
htmlacademy-adaptive/1452537-mishka-21 pull request #15
Opened 2020-12-17 05:12 UTC by Nikulichka

2020-12-17 06:09 UTC, Dima-Dim requested changes
zigzag-и вроде было svg?
В ипнутах удобнее завести отдельные блоки для радиокнопок и чекбоксов. Возможно и для других типов тоже. Файл form в 600 строк становится слишком всеобъемлющим.

2020-12-18 17:14 UTC, Dima-Dim requested changes

2020-12-18 17:14 UTC, Dima-Dim commented on source/less/blocks/form/form__container-add.less
> +.form__fieldset-add .form__legend {
Судя по неймингу это всё ещё блок form, который по критериям должен быть в файле form.
Речь была о том, что бы завести блоки вида checkbox, radio-batton и т.п. и в этих блоках делать стилизацию соответствующих участков.

2020-12-18 22:05 UTC, Nikulichka commented on source/less/blocks/form/form__container-add.less
> +.form__fieldset-add .form__legend {
Может тогда лучше переименовать containerы, убрать впереди form__? Если убрать чисто radio и checkbox инпуты, то файл form немного меньше получится, строк 400 из 600 останется, если не больше. Всё равно большой получится..

2020-12-19 06:19 UTC, Dima-Dim commented on source/less/blocks/form/form__container-add.less
> +.form__fieldset-add .form__legend {
400 это минус треть, уже хорошо. Сделать можешь как тебе удобнее, смысл в том, что бы разделить форму на более мелкие, но при этом самодостаточные блоки.

2020-12-19 15:03 UTC, Nikulichka commented on source/less/blocks/form/form__container-add.less
> +.form__fieldset-add .form__legend {
Если не так, то я больше не знаю как

2020-12-20 22:58 UTC, Nikulichka commented on source/less/blocks/form/form__container-add.less
> +.form__fieldset-add .form__legend {
Значок телефона и почты задан как placeholder и только сейчас дошло до меня, что эти значки исчезают при вводе текста. Так ведь быть не должно? Попробовала after и before, а они не работают, не понимаю почему.

2020-12-21 06:15 UTC, Dima-Dim commented on source/less/blocks/form/form__container-add.less
> +.form__fieldset-add .form__legend {
Да, лучше для них использовать псевдоэлементы. И использовать их с тегами для которых они возможны ;)

2020-12-21 06:38 UTC, Nikulichka commented on source/less/blocks/form/form__container-add.less
> +.form__fieldset-add .form__legend {
К label надо было применить?

2020-12-21 06:39 UTC, Nikulichka commented on source/less/blocks/form/form__container-add.less
> +.form__fieldset-add .form__legend {
А как структура формы в этот раз, терпимо?

2020-12-21 06:47 UTC, Dima-Dim commented on source/less/blocks/form/form__container-add.less
> +.form__fieldset-add .form__legend {
Попробуй к label, это явно более логично.

2020-12-21 06:48 UTC, Dima-Dim commented on source/less/blocks/form/form__container-add.less
> +.form__fieldset-add .form__legend {
> А как структура формы в этот раз, терпимо?

Да, стало лучше :)

2020-12-21 07:57 UTC, Nikulichka commented on source/less/blocks/form/form__container-add.less
> +.form__fieldset-add .form__legend {
Ну наконец-то!)))

2020-12-21 08:11 UTC, Nikulichka commented on source/less/blocks/form/form__container-add.less
> +.form__fieldset-add .form__legend {
Пулл-реквест закроете? Значки в инпутах уже переделала, но закоммитить только вечером смогу

2020-12-22 07:15 UTC, Dima-Dim commented
`main-nav-mobile-menu--nojs` -> `main-nav__mobile-menu--nojs`

2020-12-22 07:15 UTC, Dima-Dim approved these changes

2020-12-22 07:15 UTC, merged