Adaptive graphics for form page
htmlacademy-adaptive/1452537-mishka-21 pull request #19
Opened 2020-12-26 16:35 UTC by Nikulichka

2020-12-28 03:41 UTC, Dima-Dim requested changes
Давай попробуем лого через picture.

2020-12-28 03:41 UTC, Dima-Dim commented on source/catalog.html
> +          <svg class="main-nav__logo-img main-nav__logo-mobile" width="86" height="35" role="img" aria-label="Логотип интернет-магазина «Мишка»" fill="none" xmlns="http://www.w3.org/2000/svg">
На лекции показывали как это сделать с помощь. тега picture

2020-12-28 06:52 UTC, Nikulichka commented on source/catalog.html
> +          <svg class="main-nav__logo-img main-nav__logo-mobile" width="86" height="35" role="img" aria-label="Логотип интернет-магазина «Мишка»" fill="none" xmlns="http://www.w3.org/2000/svg">
А в теге picture как мне поменять fill при hover и active? 9 разных svg скачать?

2020-12-28 07:04 UTC, Nikulichka commented on source/catalog.html
> +          <svg class="main-nav__logo-img main-nav__logo-mobile" width="86" height="35" role="img" aria-label="Логотип интернет-магазина «Мишка»" fill="none" xmlns="http://www.w3.org/2000/svg">
Или имеете ввиду, обернуть эти svg в тег picture?

2020-12-28 07:14 UTC, Dima-Dim commented on source/catalog.html
> +          <svg class="main-nav__logo-img main-nav__logo-mobile" width="86" height="35" role="img" aria-label="Логотип интернет-магазина «Мишка»" fill="none" xmlns="http://www.w3.org/2000/svg">
Там вроде эти состояние только opacity меняют.

2020-12-28 08:13 UTC, Nikulichka commented on source/catalog.html
> +          <svg class="main-nav__logo-img main-nav__logo-mobile" width="86" height="35" role="img" aria-label="Логотип интернет-магазина «Мишка»" fill="none" xmlns="http://www.w3.org/2000/svg">
Спасибо! Я бы не додумалась)

2020-12-29 09:38 UTC, Dima-Dim requested changes
Перепроверь html validator.w3.org/nu/

2020-12-29 09:38 UTC, Dima-Dim commented on source/js/modal.js
> +function modalWindowPositionCalc (yCoord, yCoordSmall) {
Для этого же CSS есть :)

2020-12-29 09:38 UTC, Dima-Dim commented on source/less/blocks/modal.less
> +  top: 1046px;
Судя по этой цифре position: fixed;

2020-12-29 10:08 UTC, Nikulichka commented on source/js/modal.js
> +function modalWindowPositionCalc (yCoord, yCoordSmall) {
??? не понимаю...(

2020-12-29 10:19 UTC, Nikulichka commented on source/less/blocks/modal.less
> +  top: 1046px;
c fixed не работает

2020-12-29 14:30 UTC, Dima-Dim commented on source/js/modal.js
> +function modalWindowPositionCalc (yCoord, yCoordSmall) {
Расскажи, что ты тут пытаешься организовать.

2020-12-30 06:25 UTC, Nikulichka commented on source/js/modal.js
> +function modalWindowPositionCalc (yCoord, yCoordSmall) {
В коммите скинула с комментариями к modal.js

2020-12-30 07:51 UTC, Dima-Dim commented on source/js/modal.js
> +То есть нажимаешь на кнопку, а модальное окно появляется где-то вверху.
Почему не position: fixed? Он ведь именно для этого нужен.

2020-12-30 08:01 UTC, Nikulichka commented on source/js/modal.js
> +То есть нажимаешь на кнопку, а модальное окно появляется где-то вверху.
Я не особо пока понимаю разницу между absolute и fixed, делаю методом тыка, что работает в общем, то и оставляю. Попробовала задать position: fixed, окно просто не появляется, исчезает куда-то

2020-12-30 08:10 UTC, Dima-Dim commented on source/js/modal.js
> +То есть нажимаешь на кнопку, а модальное окно появляется где-то вверху.
Не совсем верный подход для учёбы на курсе. Нужно разбираться :) а если не понятно, то задавать вопросы. Тем более что материал по позиционированию разбирался на 1-ом уровне вёрстки.
Вот демка https://up.htmlacademy.ru/htmlcss/29/demos/4281#1
Вот видео с объяснением https://up.htmlacademy.ru/htmlcss/29/module/8/live

Сообщи если всё еще останутся вопросы.

2020-12-30 08:46 UTC, Nikulichka commented on source/js/modal.js
> +То есть нажимаешь на кнопку, а модальное окно появляется где-то вверху.
Это мне понятно))) мне непонятно чем position absolute в данном случае хуже position fixed

2020-12-30 09:08 UTC, Dima-Dim commented on source/js/modal.js
> +То есть нажимаешь на кнопку, а модальное окно появляется где-то вверху.
Значит не понятно :)
absolute позиционируется относительно ближайшего родителя с позиционированием не статик.
fixed позиционируется относительно видимой области браузера. Это как раз то, что ты пытаешься имитировать JS-ом.

2020-12-30 09:48 UTC, Nikulichka commented on source/js/modal.js
> +То есть нажимаешь на кнопку, а модальное окно появляется где-то вверху.
Аааа, ясненько... Простите :)

2020-12-30 10:04 UTC, Nikulichka commented on source/js/modal.js
> +То есть нажимаешь на кнопку, а модальное окно появляется где-то вверху.
отправила коммит

2020-12-31 09:16 UTC, merged