Optimized graphic for index page
htmlacademy-adaptive/1452537-mishka-21 pull request #21
Opened 2021-01-12 09:38 UTC by Nikulichka

2021-01-12 14:05 UTC, Nikulichka commented
>  [Оптимизация графики на главной странице](https://up.htmlacademy.ru/adaptive/21/user/1452537/tasks/19)
Прошу не обращать внимания пока что на всё что в папке build

2021-01-13 09:50 UTC, Dima-Dim commented
Нужно убрать build из репозитория :)

2021-01-14 06:16 UTC, Dima-Dim requested changes
source/less/style.css - это собранный css, его в репозитории тоже быть не должно.

2021-01-14 07:29 UTC, Nikulichka commented
> source/less/style.css - это собранный css, его в репозитории тоже быть не должно.

Простите(

2021-01-15 06:44 UTC, merged